### ISSUE TITLE
Add missing attributes to cover file/dataset popularity use case

### ISSUE THREAD

**Issue by vkuznet** [dmwm/rucio-tracers#23]
According to [rucio google doc](https://docs.google.com/document/d/1ZSyLat4l1iW9H2cNesmjLMiiRlg975gUwLFcZplYr28/edit#) the file and dataset popularity use-case (proposed by Andrea) requires some additional attributes which I can't find in [tracer ES](https://es-monit-st.cern.ch/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2FM,to:now%2FM))&_a=(columns:!(_source),index:%279385c0c0-6aea-11eb-9e4f-5d2f385b6b52%27,interval:auto,query:(language:kuery,query:%27%27),sort:!(metadata.timestamp,desc))).

They are:
- parent dataset
- WN hostname
- local site
- job ID
- task ID

I think all of these attributes can be extracted from FWJR (WMArchvie data) and can be added to traces output.

**Comment by ericvaandering** [comment]
Then why is this not a job for a different consumer of the FWJR data? The job of RucioTracer is to feed a specific set of data to Rucio which Rucio needs to act on. Its job is not to produce something useful for CMS long term monitoring. Loading its output down with extraneous information will, at best, increase the load on Rucio to sift through for data it needs. At worst extra fields may cause issues.

Maybe there is a misconception here. RucioTracer is not a monitoring application. It's a bridge between the FWJR monitoring and Rucio.

**Comment by vkuznet** [comment]
Because current data you extract covers more than 50% of required for data popularity use-case. Plus the missing info comes from the same data-source (FWJR). Of course we can add additional consumer which will eventually do the same job as this one. I'm not advocating that the data should be yielded to the same sink, or run together but it seems natural (from architecture point of view) to do this:
```
FWJR source -> parser -> Rucio Tracers -> ES rucio tracers
                                        -> Rucio Pop info -> ES Rucio popularity sink
```
The only difference I see is where to send the data, since all other pieces are identical to both use-cases. Because of that I also don't see need for extra service to produce this data. I view it as enrichment of current Rucio tracers.

**Comment by ericvaandering** [comment]
Let's start with a correct diagram as I'm not sure what "ES Rucio Popularity sink" is. Here's what we have currently:

FWJR source -> Rucio tracer application -> Rucio Tracer AMQ topic -> Rucio kronos daemon

Elastic search is not involved as far as I know, and it if is it's a side effect. 

Maybe @yuyiguo  can look at this after the other popularity sources are feeding data to Rucio. But this seems to me to be something wholly outside Rucio. Getting the other popularity sources supplying traces to Rucio is our highest priority for this.

**Comment by vkuznet** [comment]
Eric,
the ES I choose as potential since after we send data to MONIT, so the
actual data flow (thanks for correction) is:
FWJR source -> Rucio tracer application -> Rucio Tracer AMQ topic -> XXX
where XXX can be anything since MONIT can redirect data to any number
of destination.

Once again, don't take this request as set of actions, what I'm saying that
after evaluating Rucio monitoring use-cases I see that data-popularity one
can easily fit into existing Rucio tracer codebase to provide necessary
data. That's it.

Do what you need to do in terms of priority but to me it is clear where
changes are required to cover Rucio data-popularity use-case and this is
why I opened ticket in appropriate place.

**Comment by yuyiguo** [comment]
Currently we are continuing on the path: FWJR source -> Rucio tracer application -> Rucio Tracer AMQ topic -> Rucio kronos daemon.

We will have work on our priority list.  So I am closing this ticket.
